---
- name: checking for gcs bucket path
  shell: "gsutil list| grep -q {{ bucket_path }}"
  register: results
  failed_when: results.rc != 0

- name: "copying token to {{ dest_path }}/{{ item }}"
  shell: "gsutil rsync -r  {{ bucket_path }}{{ folder }} {{ dest_path }}"

- name: set vault environment Variables
  environment:
    VAULT_ADDR: https://clotho.broadinstitute.org:8200
#  shell: "export VAULT_ADDR=https://clotho.broadinstitute.org:8200 && echo export VAULT_ADDR=https://clotho.broadinstitute.org:8200 >> /root/.bashrc && source /root/.bashrc"
  run_once: true

- name: set vault environment Variables
  environment:
    VAULT_TOKEN: $(cat /tmp/vault-token*)
#  shell: "export VAULT_TOKEN=$(cat /tmp/vault-token*) && echo export VAULT_TOKEN=$(cat /tmp/vault-token*) >> /root/.bashrc && source /root/.bashrc"
  run_once: true
