---
- name: checking for gcs bucket path
  shell: "gsutil list -p {{ gcloud_project }}| grep -q {{ bucket_path }}"
  register: results
  failed_when: results.rc != 0

- name: "copying token to {{ dest_path }}/{{ item }}"
  shell: "gsutil rsync -r  {{ bucket_path }}{{ folder }} {{ dest_path }}"
  register: copy_token

#I tried this with environment variable but could not figure out how to source them within the same run
- name: set ansible vault environment Variable VAULT_ADDR
  shell: export VAULT_ADDR=https://clotho.broadinstitute.org:8200
  when: copy_token.stdout != "" or copy_token.changed

- name: set ansible vault environment Variable
  shell: export VAULT_TOKEN=$(cat {{ dest_path }}vault-token*)
  when: copy_token.stdout != "" or copy_token.changed
