---
- name: checking for gcs bucket path
  shell: "gsutil list -p {{ gcloud_project }}| grep -q {{ bucket_path }}"
  register: results
  failed_when: results.rc != 0

- name: "copying token to {{ dest_path }}/{{ item }}"
  shell: "gsutil rsync -x ^[^vault].*  {{ bucket_path }}{{ folder }} {{ dest_path }}"
  register: copy_token
